function finishAppNotification(){
    alert('You have closed the App.');
}

function notNumberValueNotification(){
    alert('The entered value is not a number, please repeat your action!');
}


function getValueFromUser(){
    let valueFromUser = prompt('Please enter the number for guessing. The number will be generated in range from 0 to 100');

    if (valueFromUser !== null) {
        valueFromUser = Number(valueFromUser);

        if (Number.isNaN(valueFromUser)) {
            notNumberValueNotification();
            valueFromUser = getValueFromUser();
        }

        return valueFromUser;
    }

    return valueFromUser

}

function generateRandomValue(){
    return Math.round(Math.random() * 100);
}



alert ('You have to guess the number which will be generated by the system');
let valueFromUser = getValueFromUser();

if (valueFromUser !== null) {
    let generatedValue = generateRandomValue();

    console.log(valueFromUser);
    console.log(generatedValue);

    if (valueFromUser === generatedValue) {
        alert('CONGRATULATED!!! It is matched');
    } else {
        alert('FAIL!!! It was close');
    }
} else {
 finishAppNotification();
}







